### ISSUE TITLE
Auto full screen or not

### ISSUE THREAD

**Issue by IzetopeDev** [FelixIsaac/kopi-cats#6]
Let's decide here

**Comment by icesotope41** [comment]
We

**Comment by Frostbyte-Cat1** [comment]
I am for it

**Comment by IzetopeDev** [comment]
i don't mind tbh

**Comment by FelixIsaac** [comment]
We can do it like Minecraft's way of doing it. Default to fullscreen, but in the options can just make it windowed.

**Comment by IzetopeDev** [comment]
> We can do it like Minecraft's way of doing it. Default to fullscreen, but in the options can just make it windowed.

do we need to add additional code other than the fullscreen code? or is it already default?
